### ISSUE TITLE
Exception on system with Zen 3 + RX 6800 XT

### ISSUE THREAD

**Issue by DevTechProfile** [Mixaill/Mixaill.HwInfo#1]
We've tested the Nuget on different systems.

Error while getting PCI device infos.","@l":"Error","@x":"System.ComponentModel.Win32Exception (0x80004005): Element not found\r\n   at Mixaill.HwInfo.SetupApi.DeviceInfoSet.GetProperty(SP_DEVINFO_DATA devInfoData, DEVPROPKEY propKey)\r\n   at Mixaill.HwInfo.SetupApi.DeviceInfoFactory.Create(DeviceInfoSet devInfoSet, SP_DEVINFO_DATA devInfo)\r\n   at Mixaill.HwInfo.SetupApi.DeviceInfoSet.Initialize()\r\n   at CapFrameX.SetupAPI.NetStandard.SetupAPIWrapper..ctor(ILogger`1 logger) in C:\Users\taxxo\Source\Repos\CapFrameX\source\CapFrameX.SetupAPI.NetStandard\SetupAPIWrapper.cs:Line21.","SourceContext":"CapFrameX.SetupAPI.NetStandard.SetupAPIWrapper"}

Can you do anything with the info?

**Comment by Mixaill** [comment]
Please test demo executable with last commit and attach the screenshot (even if exception was fixed)

[Mixaill.HwInfo.SetupApi.Demo.zip](https://github.com/Mixaill/Mixaill.HwInfo/files/6472584/Mixaill.HwInfo.SetupApi.Demo.zip)

**Comment by Taxxor90** [comment]
![Screenshot 2021-05-13 155644](https://user-images.githubusercontent.com/45570250/118135921-d700fd80-b403-11eb-8204-4a96004929ca.png)
Nothing happens when trying to execute the file, this is what eventviewer shows

**Comment by Mixaill** [comment]
It requires .NET 5.0

https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-5.0.6-windows-x64-installer

**Comment by Taxxor90** [comment]
With 5.0 installed, although the exception CX is throwing hasn't changed.
Vega56 and 2080Ti were cards previously installed in the system

![mixaill](https://user-images.githubusercontent.com/45570250/118137132-25fb6280-b405-11eb-965c-728bd54da3ea.png)

**Comment by Mixaill** [comment]
Please replace `Mixaill.HwInfo.SetupApi.dll` in the CapFrameX folder with this one

[Mixaill.HwInfo.SetupApi.zip](https://github.com/Mixaill/Mixaill.HwInfo/files/6472933/Mixaill.HwInfo.SetupApi.zip)

**Comment by Mixaill** [comment]
>Vega56 and 2080Ti were cards previously installed in the system

That's the bug, I do not exclude cards which are not installed at this moment.

**Comment by Taxxor90** [comment]
Seems to work, no exception in the log file

**Comment by Mixaill** [comment]
[Mixaill.HwInfo.SetupApi.Demo_2.zip](https://github.com/Mixaill/Mixaill.HwInfo/files/6473043/Mixaill.HwInfo.SetupApi.Demo_2.zip)

@Taxxor90 please check this demo, you should see only one GPU which is currently installed

**Comment by Taxxor90** [comment]
Yes that's the case

**Comment by Mixaill** [comment]
Nice.

Fixed in  https://github.com/Mixaill/Mixaill.HwInfo/commit/c85733abec2ab3584fd07e6c29d6fcef1e5149c0 https://github.com/Mixaill/Mixaill.HwInfo/commit/cb39af3a0cbe103a71ba953a2fd748da3a14185a

**Comment by Mixaill** [comment]
CapFrameX PR: https://github.com/CXWorld/CapFrameX/pull/168
