### ISSUE TITLE
Crash when "vulkan-1.dll" is missing

### ISSUE THREAD

**Issue by DevTechProfile** [Mixaill/Mixaill.HwInfo#2]
The first error is 

"Error while getting Resizable Bar software status.",
"Could not find or load the native library: vulkan-1.dll Attempted: "vulkan-1.dll", "C:\Program Files (x86)\CapFrameX\vulkan-1.dll""

But this is catched and only a log entry is written. But to my surprise it leads to an app crash.

"Referência de objeto não definida para uma instância de um objeto."
em Mixaill.HwInfo.Vulkan.Vulkan.Dispose(Boolean disposing)\r\n   em Mixaill.HwInfo.Vulkan.Vulkan.Finalize()"

This error message is from a user who uploaded a crash report.

**Comment by Mixaill** [comment]
fixed in 1931ace397c412b71fbc42304148e6d0a9037ca9
